name: BedrockSupport
version: '1.0'
main: com.jellypudding.fakePlayers.FakePlayers
api-version: '1.21'
description: "Helps with supporting Bedrock clients joining the server"
author: AlphaAlex115
depend: [SimpleTPA]