name: FakePlayers
version: '1.0-SNAPSHOT'
main: com.jellypudding.fakePlayers.FakePlayers
api-version: '1.21'
description: "Creates fake players and hides plugin information"
author: AlphaAlex115
commands:
  fakeplayers:
    description: "FakePlayers admin commands"
    usage: "/fakeplayers reload"
permissions:
  fakeplayers.showinfo:
    description: "Allows the user to view plugin information via commands such as /plugins, /pl, /help, and /?."
    default: op
  fakeplayers.reload:
    description: "Allows reloading the plugin configuration"
    default: op